#+title: Bases
#+date:
#+language: es
#+layout: page
#+options: toc:nil

#+BEGIN_CENTER
XXXI Olimpiada Mexicana de Matemáticas - Etapa Estatal de Hidalgo
<br />
<br />
#+END_CENTER

1. Podrán participar todos los alumnos inscritos en el *nivel medio* o
   *medio superior*.

2. Los estudiantes interesados podrán inscribirse en una de *dos
   modalidades*: como parte del *equipo de su institución*, o de
   *manera independiente*.

3. Los *equipos representativos* de cada institución estarán formados
   por a lo más 9 estudiantes por escuela (secundaria o
   bachillerato). En el caso de las secundarias, a lo más tres alumnos
   de cada grado escolar. En el caso del nivel bachillerato a lo más
   tres alumnos de
   los dos últimos semestres, y a lo más tres de tercero y cuarto semestre.
   Las instituciones
   participantes deben pertenecer al Estado de Hidalgo.
   
4. Alumnos de *quinto o sexto grado de primaria* podrán participar
   *solo en la modalidad independiente*, y para efectos
   del concurso serán considerados como estudiantes de primero de
   secundaria.
   
5. Los equipos representativos deberán pertenecer a *escuelas del
   Estado de Hidalgo*. Esta restricción *no aplica para registros
   independientes*.
   
6. La participación, tanto por escuela como individual, es *gratuita*.

7. El registro de los equipos representativos se hará en línea en la
   página http://otech.uaeh.edu.mx/ommh/.  La documentación
   correspondiente de cada participante (acta de nacimiento y
   constancia de estudios) deberá presentarse al coordinador de la
   sede correspondiente, quien validará la inscripción.  Los
   documentos pueden presentarse en original, copia o digital.
   
8. Los registros de *participantes independientes* se realizarán de
   manera exclusiva por correo electrónico. Los interesados deberán
   enviar un correo *desde su correo personal* o de su padre, madre o
   tutor a la dirección [[mailto:integramate@gmail.com][integramate@gmail.com]] indicando el nombre
   completo del alumno, su grado escolar y la escuela a la que
   pertenece. En archivo adjunto deberá anexarse la documentación
   referida en el punto anterior. Solamente se podrá efectuar *un
   registro por cuenta de correo* electrónico.
   
9. El *periodo de inscripciones* se abre el 14 de diciembre de 2016 y se
   cierra el 17 de febrero de 2017.

10. El evento se llevará a cabo en *dos etapas*.

11. La *primera etapa* tendrá lugar el 25 de febrero,
    de 10:00 a 13:30 horas en las sedes señaladas en la convocatoria y
    consistirá en un examen de opción múltiple.

12. Los alumnos con *puntuaciones más altas* de secundaria y los alumnos
    con puntuaciones más altas de nivel medio superior, serán los
    invitados a participar en *la segunda etapa* del concurso.
    
13. La *lista de alumnos ganadores que pasan a la segunda etapa*
    estará publicada el 13 de marzo en la página web de
    la Olimpiada Hidalguense de Matemáticas ([[http://www.ohm.org.mx][www.ohm.org.mx]]) y en la
    página de facebook ([[http://www.facebook.com/ohmates][www.facebook.com/ohmates]]).

14. La *segunda etapa* se realizará el sábado 18 de marzo de 10:00 a
    14:00 horas en instalaciones de la Universidad Autónoma del Estado
    de Hidalgo.
    
15. Se *premiará con un primer o un segundo lugar* a todos los
    estudiantes que se presenten al examen de la segunda etapa.
    
16. Los alumnos de instituciones del Estado de Hidalgo que obtengan
    uno de los premios de *Primer Lugar de Secundaria o Primer Lugar
    de Bachillerato* y que no estén cursando el último año de
    bachillerato ni hayan nacido antes del 1 de agosto de 1999,
    pasarán a formar parte de la *Preselección del Estado de Hidalgo
    2017.*
    
17. La participación en la preselección por parte de estudiantes de
    instituciones pertenecientes a *otras entidades federativas*
    estará supeditada a los lineamientos y la autorización por parte
    de la Olimpiada Mexicana de Matemáticas.
    
18. Los alumnos que, representando al Estado de Hidalgo, hayan
    obtenido *medalla o mención honorífica* en la XXX Olimpiada
    Mexicana de Matemáticas (Acapulco 2016), y que sean elegibles
    pasarán a formar parte de la Preselección del Estado de Hidalgo
    2017, independientemente de su participación en la olimpiada
    estatal.
    
19. De la Preselección del Estado de Hidalgo 2017 se seleccionará a
    los seis miembros de la *Selección del Estado de Hidalgo*, que
    representarán a la entidad en la XXXI Olimpiada Mexicana de
    Matemáticas, a celebrarse en el mes de noviembre del año 2017.
    
20. El Comité Olímpico nombrará una *Comisión de Examen*, cuyas
    resoluciones sobre el resultado del concurso serán inapelables.

21. Se otorgará *constancia de participación* a todos los alumnos
    participantes, a los profesores entrenadores y a los coordinadores
    de las sedes. Las constancias *serán enviadas en formato digital*
    a la dirección de correo electrónico registrada.
    
22. No se realizarán *registros extemporáneos*.

23. Cualquier *situación no prevista* en este documento será resuelta
    por el Comité Olímpico Estatal de Matemáticas.

#+BEGIN_CENTER
<br />
<br />
Comité Olímpico Estatal de Matemáticas
<br />
<br />
#+END_CENTER

#+BEGIN_CENTER
Dr. Orlando Ávila Pozos
#+END_CENTER

#+BEGIN_CENTER
Dr. Fernando Barrera Mora
#+END_CENTER

#+BEGIN_CENTER
Dr. Ricardo Cruz Castillo
#+END_CENTER

#+BEGIN_CENTER
Dr. Benjamín A. Itzá Ortíz
#+END_CENTER

#+BEGIN_CENTER
Dr. Rubén A. Martínez Avendaño
#+END_CENTER

#+BEGIN_CENTER
Dr. Federico Menéndez Conde Lara
#+END_CENTER

#+BEGIN_CENTER
Dr. Rafael Villarroel Flores
#+END_CENTER


# Local Variables:
# org-hide-emphasis-markers: nil
# End:
