#+title: Bases
#+date:
#+language: es
#+layout: page
#+options: toc:nil

#+BEGIN_CENTER
XXIX Olimpiada de Matemáticas del Estado de Hidalgo
<br />
<br />
#+END_CENTER

1. Podrán participar todos los alumnos inscritos en el *nivel medio* o
   *medio superior*.

2. Los estudiantes interesados podrán inscribirse en una de *dos
   modalidades*: como parte del *equipo de su institución*, o de
   *manera independiente*.

3. Los *equipos representativos* de cada institución estarán formados
   por a lo más 9 estudiantes por escuela (secundaria o
   bachillerato). En el caso de las secundarias, a lo más tres alumnos
   de cada grado escolar. En el caso del nivel bachillerato a lo más
   la tercera parte de los inscritos por escuela podrán estar cursando
   los dos últimos semestres, y al menos una tercera parte deberá
   estar cursando primero o segundo semestre. Las instituciones
   participantes deben pertenecer al Estado de Hidalgo.
   
4. Alumnos de *quinto o sexto grado de primaria* podrán participar
   solo en la modalidad de participación individual, y para efectos
   del concurso serán considerados como estudiantes de primero de
   secundaria.
   
5. El registro de equipos representativos es exclusivo para *escuelas
   del Estado de Hidalgo*. Esta restricción no aplica para registros
   de participación independientes.
   
6. La inscripción, tanto por escuela como individual, es *gratuita*.

7. Cada institución deberá inscribir a su equipo representativo en la
   *Sede Regional* más cercana. Deberá presentarse al Coordinador de
   la Sede (o a la persona a quien el coordinador delegue para tal
   fin) la documentación correspondiente, consistente en: acta de
   nacimiento y constancia de estudios de cada alumno
   participante. Los documentos pueden presentarse en original, copia
   o incluso escaneadas.
   
8. Los registros de *participantes independientes* se realizarán de
   manera exclusiva por correo electrónico. Los interesados deberán
   enviar un correo a [[mailto:integramate@gmail.com][integramate@gmail.com]] indicando el nombre
   completo del alumno, su grado escolar y la escuela a la que
   pertenece. La documentación referida en el punto anterior podrá
   enviarse escaneada o bien presentarse físicamente en el Área
   Académica de Matemáticas y Física de la UAEH.
   
9. El *periodo de inscripciones* se abre el 5 de diciembre de 2015 y se
   cierra el 30 de enero de 2016.

10. El evento se llevará a cabo en *dos etapas*.

11. La *primera etapa* tendrá lugar el sábado 6 de febrero de 2015, de
    10:00 a 13:00 horas en las sedes señaladas en la convocatoria y
    consistirá en un examen de opción múltiple. Puedes pedir al
    Coordinador de la Sede el examen de práctica.
    
12. Los *resultados de la primer etapa* podrán ser consultados a
    partir del día 4 de marzo en la página web de la Olimpiada
    Hidalguense de Matemáticas ([[http://www.ohm.org.mx][www.ohm.org.mx]]) y en la página de
    facebook ([[http://www.facebook.com/ohmates][www.facebook.com/ohmates]]).
    
13. Los alumnos con puntuaciones más altas de secundaria y los alumnos
    con puntuaciones más altas de nivel medio superior, serán los
    invitados a participar en *la segunda etapa* del concurso.
    
14. La *segunda etapa* se realizará el día sábado 27 de febrero de
    2015 de 10:00 a 14:00 horas en instalaciones de la Universidad
    Autónoma del Estado de Hidalgo. Ésta consistirá en un examen
    escrito. Los exámenes de concursos anteriores pueden ser
    consultados en la página [[http://www.ohm.org.mx/][www.ohm.org.mx]]
    
15. Se *premiará con un primer o un segundo lugar* a todos los
    estudiantes que se presenten al examen de la segunda etapa.
    
16. Los alumnos de instituciones del Estado de Hidalgo que obtengan
    uno de los premios de Primer Lugar de Secundaria o bien de Primer
    Lugar de Bachillerato, que no estén cursando el último año de
    bachillerato ni hayan nacido antes del 1 de agosto de 1998,
    pasarán a formar parte de la *Preselección del Estado de Hidalgo
    2016.*
    
17. La participación en la preselección por parte de estudiantes de
    instituciones pertenecientes a *otras entidades federativas*
    estará supeditada a los lineamientos y la autorización por parte
    de la Olimpiada Mexicana de Matemáticas.
    
18. Los alumnos que, representando al Estado de Hidalgo, hayan
    obtenido *medalla o mención honorífica* en la XXIX Olimpiada
    Mexicana de Matemáticas (Guadalajara 2015), y que sean elegibles
    para la olimpiada del siguiente año pasarán a formar parte de la
    Preselección del Estado de Hidalgo 2016, independientemente de su
    participación en la olimpiada estatal.
    
19. De la Preselección del Estado de Hidalgo 2016 se seleccionará a
    los seis miembros de la *Selección del Estado de Hidalgo*, que
    representarán a la entidad en la XXX Olimpiada Mexicana de
    Matemáticas, a celebrarse en el mes de noviembre del año 2016.
    
20. El Comité Olímpico nombrará una *Comisión de Examen*, cuyas
    resoluciones sobre el resultado del concurso serán inapelables.

21. Se otorgará *constancia de participación* a todos los alumnos
    participantes, a los profesores entrenadores y a los coordinadores
    de las sedes. Las constancias de alumnos se entregarán el día del
    primer examen; las demás podrán recogerse con el coordinador de
    sede correspondiente del 6 de febrero al 27 de abril de 2016; no
    se entregarán constancias después de esa última fecha.
    
22. No se realizarán *inscripciones extemporáneas*.

23. Cualquier *situación no prevista* en este documento será resuelta
    por el Comité Olímpico Estatal de Matemáticas.

#+BEGIN_CENTER
<br />
<br />
Comité Olímpico Estatal de Matemáticas
<br />
<br />
#+END_CENTER

#+BEGIN_CENTER
Dr. Orlando Ávila Pozos
#+END_CENTER

#+BEGIN_CENTER
Dr. Fernando Barrera Mora
#+END_CENTER

#+BEGIN_CENTER
Dr. Ricardo Cruz Castillo
#+END_CENTER

#+BEGIN_CENTER
Dr. Benjamín A. Itzá Ortíz
#+END_CENTER

#+BEGIN_CENTER
Dr. Rubén A. Martínez Avendaño
#+END_CENTER

#+BEGIN_CENTER
Dr. Federico Menéndez Conde Lara
#+END_CENTER

#+BEGIN_CENTER
Dr. Rafael Villarroel Flores
#+END_CENTER


# Local Variables:
# org-hide-emphasis-markers: nil
# End:
