#+title: Sedes regionales
#+date:
#+language: es
#+layout: page
#+options: toc:nil

* Actopan
COBAEH Actopan\\
Carr. Daxtha - San Salvador No. 17\\
(771) 2383935\\
Coord. Exequiel López Álvarez\\
ohmactopan@gmail.com\\

* Cd. Sahagún
Escuela Superior Cd. Sahagún UAEH\\
Carr. Cd. Sahagún - Otumba Km. 3.5\\
(771) 71720000 ext. 5300\\
Coord. Ma. Rafaela Mohedano Juárez\\
ohmcdsahagun@gmail.com\\

* Huejutla
Escuela Superior Huejutla UAEH\\
Carr. México-Tampico Km. 217\\
(771) 7172000 ext. 5880\\
Coord. Virginia Arguelles Pascual\\
ohmhuejutla@gmail.com\\

* Huichapan
Instituto Don Bosco\\
C. Patini No. 42\\
(761) 7822251\\
Coord. Juan Ignacio Arriola Ruiz\\
ohmhuichapan@gmail.com\\

* Ixmiquilpan
Preparatoria Jesús Ángeles Contreras\\
C. Paseo del Roble s/n\\
(759) 7232531\\
Coord. Marco Antonio de la Concha Vargas\\
ohmixmiquilpan@gmail.com\\

* Metztitlán
CECYTEH Metztitlán\\
Av. Tepeyaca No. 100\\
(774) 7430972\\
Coord. Rosa Ma. Reyes Fernández\\
ohmmetztitlan@gmail.com\\

* Pachuca
Colegio Jorge Berganza\\
Blvd. Luis Donaldo Colosio No. 184\\
(771) 7135170\\
Coord. Carlos Villegas Terrazas\\
ohmpachuca@gmail.com\\

* Pisaflores
COBAEH Pisaflores\\
Av. Independencia s/n\\
Col. Cuartel Morelos\\
(772) 1315960\\
Coord. Ricardo Ruiz Solis\\
ohmpisaflores@gmail.com\\

* Tenango
COBAEH Tenango de Doria\\
C. Bachilleres No. 7\\
(776) 7553560\\
Coord. Ángel Brito Vega\\
ohmtenango@gmail.com\\

* Tizayuca
COBAEH Tizayuca\\
Blvd. de la Cruz Sur S/N\\
Fracc. Haciendas de Tizayuca 3era. Sección\\
(779) 7966687\\
Coord. Alejandro Quiroz Rodríguez\\
ohmtizayuca@gmail.com\\

* Tlanchinol
COBAEH Tlanchinol\\
C. Dorias s/n, Barrio Morelos\\
(774) 9740124\\
Coord. Pablo Vite Martínez\\
ohmtlanchinol@gmail.com\\

* Tula
CETIS 91\\
Calle Deportiva 3, Huerto Nantzha\\
(773) 7324533, (773) 1148104\\
Coord. Marisol Ortiz Gálvez\\
ohmtula@gmail.com\\

* Tulancingo
Colegio Jorge Berganza\\
C. Matamoros No. 303\\
Col. Felipe Ángeles\\
(775) 7533544\\
Coord. Evelyn Espino Alvarado\\
ohmtulancingo@gmail.com\\

* Zimapán
Escuela Superior Zimapán UAEH\\
Domicilio Conocido\\
(759) 7282982 ext. 5901\\
Coord. Edgar García Maldonado\\
ohmzimapan@gmail.com\\
