#+title: Sedes regionales
#+date:
#+language: es
#+layout: page
#+options: toc:nil

* Actopan
COBAEH Actopan\\
Carr. Daxtha - San Salvador No. 17\\
Coord. Exequiel López Álvarez\\
(771) 2383-935\\
ohmactopan@gmail.com\\

* Cd. Sahagún
ES de Cd. Sahagún - UAEH\\
Carr. Cd. Sahagún - Otumba Km. 3.5\\
Coord. Rafaela Mohedano Juárez\\
(771) 7172-000 ext. 5300\\
ohmcdsahagun@gmail.com\\

* Huejutla
ES de Huejutla UAEH\\
Carr. México-Tampico km. 217\\
Coord. Virginia Argüelles Pascual\\
(771) 7172-000 ext. 5880\\
ohmhuejutla@gmail.com\\

* Huichapan
Instituto Don Bosco\\
Patoni 42\\
Coord. Juan Ignacio Arriola Ruiz\\
(761) 7822-251\\
ohmhuichapan@gmail.com\\

* Ixmiquilpan
Prep. Jesús Ángeles Contreras\\
Paseo del Roble s/n\\
Coord. Marco Antonio de la Concha Vargas\\
(759) 723-2531\\
ohmixmiquilpan@gmail.com\\

* Ixtlahuaco
Preparatoria Ixtlahuaco - UAEH\\
Barrio Santa Lucía S/N\\
(771) 7172-000 ext 4801\\
OMMIxtlahuaco18@gmail.com\\

* Metztitlán
CECYTEH Metztitlán\\
Av. Tepeyaca 100\\
Coord. Rosa Reyes Fernández\\
(774) 7430-972\\
ohmmetztitlan@gmail.com\\

* Pachuca
Colegio Miguel de Cervantes Saavedra
Colegio Cervantes 103. Fracc. Colosio
Coord. Ingrid Rivera Raygadas\\
(771) 7180-101\\
ohmpachuca@gmail.com\\

* Pisaflores
COBAEH Pisaflores\\
Av. Independencia s/n\\
Coord. Pedro Martínez De La Cruz\\
(772) 1315-960\\
OMMPisaflores18@gmail.com\\

* Tenango de Doria
COBAEH Tenango\\
Bachilleres 7\\
Coord. Ángel Brito Vega\\
(776) 7553-560\\
ohmtenango@gmail.com\\

* Tizayuca
COBAEH Tizayuca\\
Blvd. de la Cruz s/n\\
(779) 7966-687\\
Coord. Alejandro Quiroz Rodríguez\\
ohmtizayuca@gmail.com\\

* Tlanchinol
COBAEH Tlanchinol\\
Dorias s/n, Barrio Morelos\\
Coord. Pablo Vite Martínez\\
(774) 9740-124\\
ohmtlanchinol@gmail.com\\

* Tula de Allende
CETIS 91\\
Deportiva 3, Nantzha\\
Coord. Marisol Ortiz Gálvez\\
(773) 7324-533\\
ohmtula@gmail.com\\

* Tulancingo
Colegio Jorge Berganza\\
Matamoros 303\\
Coord. Evelyn Espino Alvarado\\
(775) 7533-544\\
ohmtulancingo@gmail.com\\

* Zimapán
ES de Zimapán - UAEH\\
Jorge Preisser Terán 89\\
Coord. Edgar García Maldonado\\
(759) 7282-982\\
ohmzimapan@gmail.com\\
